# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5407845b9d963e86f883a6208e4e8b6f"
name = "Voice Ai"
application_url = "https://privileges-raised-northern-interview.trycloudflare.com"
embedded = true
handle = "voice-ai-5"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[dev]
# Debug mode configuration
debug_mode = true
log_level = "debug"
enable_console_logs = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags"

[auth]
redirect_urls = ["https://privileges-raised-northern-interview.trycloudflare.com/auth/callback", "https://privileges-raised-northern-interview.trycloudflare.com/auth/shopify/callback", "https://privileges-raised-northern-interview.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
